# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy 

In [12]:
!pip install Numpy

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

In [16]:
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

In [4]:
data = np.array([1, 2, 3, 4, 5])
print(data)
print(len(data))
print(type(data))
print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

In [24]:
twoD_array = np.array([[2, 5, 9], [5, 4, 3]])
print(twoD_array)
print(data[4])
print(data[0:3])
unsorted_data = np.array([5, 8, 6, 4, 7, 2, 3, 1, 0])
print(np.sort(unsorted_data))
alphabetically_unsorted_data=np.array(['kiwi', 'berry', 'pear'])
print(np.sort(alphabetically_data))

[[2 5 9]
 [5 4 3]]
5
[1 2 3]
[0 1 2 3 4 5 6 7 8]
['berry' 'kiwi' 'pear']


### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

In [20]:
arr = np.array([3, 2, 14, 9, 10, 12, 9])
indexes = np.where(arr == 9)
print(indexes)

(array([3, 6]),)


### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

In [22]:
arr1 = np.array([9, 5, 8])
arr2 = np.array([55, 89, 76])
print(np.concatenate((arr1, arr2)))

[ 9  5  8 55 89 76]
